name: Test reward scripts
on:
  push:
  workflow_dispatch:

jobs:
  test-contracts:
    name: Test reward scripts
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install xxd

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Pip installs deps
        run: pip install -r requirements.txt --require-hashes
        working-directory: ./reward

      - name: Run merkle test
        run: python merkle_test.py
        working-directory: ./reward

      - name: Run tests
        run: python _test_.py
        working-directory: ./reward
