name: Contract tests
on:
  push:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./contracts

jobs:
  test-contracts:
    name: Test contracts
    env:
      MAINNET_ETHEREUM_URL: ${{ secrets.MAINNET_ETHEREUM_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-v1-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-node

      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm i
      - run: npm run compile
      - run: npm run typechain
      - run: npm run test
